// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"trivium/cmd/app/di"
	"trivium/internal/domain/usecase"
	"trivium/internal/presentation/controller"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	authRepositorier := cmd.NewFirebaseRepository()
	authUseCase := usecase.NewAuthUseCase(authRepositorier)
	authController := controller.NewAuthController(authUseCase)
	statusController := controller.NewStatusController()
	httpRepositorier := cmd.NewHttpRepository()
	appServer := cmd.NewAppServer(authController, statusController, httpRepositorier)
	app := &App{
		Server: appServer,
	}
	return app, nil
}

// wire.go:

type App struct {
	Server cmd.ServerStarter
}
